run Yarn lint

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -2,186 +2,186 @@
 
 version: 2.1
 orbs:
-  coverage-reporter: codacy/coverage-reporter@10.0.3
+    coverage-reporter: codacy/coverage-reporter@10.0.3
 executors:
-  # Define a machine who has support for docker compose 3.7
-  standard:
-    machine:
-      image: ubuntu-1604:201903-01
-    working_directory: ~/repo
-  test:
-    docker:
-      - image: gsmainclusivetechlab/interop-php-fpm:latest
-      - image: circleci/mysql:5.7
-        environment:
-          MYSQL_ROOT_HOST: "%"
-          MYSQL_ROOT_PASSWORD: developer
-          MYSQL_DATABASE: itp-test-control
-          MYSQL_USER: itp-test-control
-          MYSQL_PASSWORD: developer
-        command: [--max-allowed-packet=536870912]
-          
-    working_directory: ~/repo
+    # Define a machine who has support for docker compose 3.7
+    standard:
+        machine:
+            image: ubuntu-1604:201903-01
+        working_directory: ~/repo
+    test:
+        docker:
+            - image: gsmainclusivetechlab/interop-php-fpm:latest
+            - image: circleci/mysql:5.7
+              environment:
+                  MYSQL_ROOT_HOST: '%'
+                  MYSQL_ROOT_PASSWORD: developer
+                  MYSQL_DATABASE: itp-test-control
+                  MYSQL_USER: itp-test-control
+                  MYSQL_PASSWORD: developer
+              command: [--max-allowed-packet=536870912]
+
+        working_directory: ~/repo
 jobs:
-  build:
-    executor: standard
-    
-    steps:
-      - checkout
+    build:
+        executor: standard
 
-      - run: 
-          name: Generate configuration files
-          command: make init
+        steps:
+            - checkout
 
-      - run: 
-          name: Run docker containers
-          command: | 
-            make run
-            sleep 15
-          
-      - restore_cache: 
-          keys:
-            - composer-v2-{{ checksum "src/composer.lock" }}
-            - composer-v2-
-               
-      - restore_cache: 
-          keys:
-            - node-v2-{{ checksum "src/package-lock.json" }}
-            - node-v2-
+            - run:
+                  name: Generate configuration files
+                  command: make init
 
-      - run: 
-          name: Install Componser and Node dependecies
-          command: make install
-      
-      - save_cache:
-          key: composer-v2-{{ checksum "src/composer.lock" }}
-          paths:
-            - src/vendor
-      
-      - save_cache:
-          key: node-v2-{{ checksum "src/package-lock.json" }}
-          paths:
-            - src/node_modules
+            - run:
+                  name: Run docker containers
+                  command: |
+                      make run
+                      sleep 15
 
-      - run: 
-          name: Check installation
-          command: |
-            FILE=./runtime/installed
-            if test -f "$FILE"; then
-                echo "Installation succesful"
-            else 
-                echo "Installation fail"
-                exit 2
-            fi
-         
-  test-run:
-    executor: test
-    
-    steps:
-      - checkout
-       
-      - run:
-          name: Update php.ini
-          command: sudo cp build/php-ini-development.ini /usr/local/etc/php/conf.d/zz-force-conf.ini
-          
-      - run: 
-          name: Generate configuration files
-          command: make init
-            
-      - restore_cache: 
-          keys:
-            - composer-v1-test{{ checksum "src/composer.lock" }}
-            - composer-v1-test
-     
-      - restore_cache: 
-          keys:
-            - node-v1-test{{ checksum "src/package-lock.json" }}
-            - node-v1-test
-            
-      - run: 
-          name: Install Componser dependecies
-          command: |
-            sleep 15
-            cd src
-            make install
-      
-      - save_cache:
-          key: composer-v1-test{{ checksum "src/composer.lock" }}
-          paths:
-            - src/vendor
-            
-      - save_cache:
-          key: node-v1-test{{ checksum "src/package-lock.json" }}
-          paths:
-            - src/node_modules
-            
-      - run:
-          name: Run Tests
-          command: |
-            cd src
-            make test
-          
-      - run:
-          name: Run Tests Coverage
-          command: |
-            cd src
-            make test-coverage
- 
-      - store_test_results:
-          path: src/tests/results
-      - store_artifacts:
-          path: src/tests/results
-      - store_artifacts:
-          path: src/tests/Browser/screenshots
-          
-      - persist_to_workspace:      
-          root: ~/repo/src/tests
-          paths:
-            - results
-          
-  test-coverage-codacy:
-    docker:
-      - image: gsmainclusivetechlab/interop-php-fpm:latest
-    working_directory: ~/repo
-    
-    steps:
-      - attach_workspace:
-          at: ~/repo/src/tests
-          
-      - coverage-reporter/send_report:
-          coverage-reports: src/tests/results/coverage-report-clover/clover.xml
-          project-token: $CODACY_PROJECT_TOKEN
-      
-      - run:
-          name: Copy codacy json report to artifact
-          command: sudo cp /var/tmp/codacy-coverage-*.json ~/repo/src/tests/results/
-          
-      - store_test_results:
-          path: src/tests/results
-      - store_artifacts:
-          path: src/tests/results
-    
+            - restore_cache:
+                  keys:
+                      - composer-v2-{{ checksum "src/composer.lock" }}
+                      - composer-v2-
+
+            - restore_cache:
+                  keys:
+                      - node-v2-{{ checksum "src/package-lock.json" }}
+                      - node-v2-
+
+            - run:
+                  name: Install Componser and Node dependecies
+                  command: make install
+
+            - save_cache:
+                  key: composer-v2-{{ checksum "src/composer.lock" }}
+                  paths:
+                      - src/vendor
+
+            - save_cache:
+                  key: node-v2-{{ checksum "src/package-lock.json" }}
+                  paths:
+                      - src/node_modules
+
+            - run:
+                  name: Check installation
+                  command: |
+                      FILE=./runtime/installed
+                      if test -f "$FILE"; then
+                          echo "Installation succesful"
+                      else 
+                          echo "Installation fail"
+                          exit 2
+                      fi
+
+    test-run:
+        executor: test
+
+        steps:
+            - checkout
+
+            - run:
+                  name: Update php.ini
+                  command: sudo cp build/php-ini-development.ini /usr/local/etc/php/conf.d/zz-force-conf.ini
+
+            - run:
+                  name: Generate configuration files
+                  command: make init
+
+            - restore_cache:
+                  keys:
+                      - composer-v1-test{{ checksum "src/composer.lock" }}
+                      - composer-v1-test
+
+            - restore_cache:
+                  keys:
+                      - node-v1-test{{ checksum "src/package-lock.json" }}
+                      - node-v1-test
+
+            - run:
+                  name: Install Componser dependecies
+                  command: |
+                      sleep 15
+                      cd src
+                      make install
+
+            - save_cache:
+                  key: composer-v1-test{{ checksum "src/composer.lock" }}
+                  paths:
+                      - src/vendor
+
+            - save_cache:
+                  key: node-v1-test{{ checksum "src/package-lock.json" }}
+                  paths:
+                      - src/node_modules
+
+            - run:
+                  name: Run Tests
+                  command: |
+                      cd src
+                      make test
+
+            - run:
+                  name: Run Tests Coverage
+                  command: |
+                      cd src
+                      make test-coverage
+
+            - store_test_results:
+                  path: src/tests/results
+            - store_artifacts:
+                  path: src/tests/results
+            - store_artifacts:
+                  path: src/tests/Browser/screenshots
+
+            - persist_to_workspace:
+                  root: ~/repo/src/tests
+                  paths:
+                      - results
+
+    test-coverage-codacy:
+        docker:
+            - image: gsmainclusivetechlab/interop-php-fpm:latest
+        working_directory: ~/repo
+
+        steps:
+            - attach_workspace:
+                  at: ~/repo/src/tests
+
+            - coverage-reporter/send_report:
+                  coverage-reports: src/tests/results/coverage-report-clover/clover.xml
+                  project-token: $CODACY_PROJECT_TOKEN
+
+            - run:
+                  name: Copy codacy json report to artifact
+                  command: sudo cp /var/tmp/codacy-coverage-*.json ~/repo/src/tests/results/
+
+            - store_test_results:
+                  path: src/tests/results
+            - store_artifacts:
+                  path: src/tests/results
+
 workflows:
-  version: 2
-  build_and_test:
-    jobs:
-      - build:
-          filters:
-            branches:
-              only:
-                - master
-                - develop
-      - test-run:
-          filters:
-            branches:
-              only:
-                - master
-                - develop
-      - test-coverage-codacy:
-          filters:
-            branches:
-              only:
-                - master
-                - develop
-          requires:
-            - test-run
+    version: 2
+    build_and_test:
+        jobs:
+            - build:
+                  filters:
+                      branches:
+                          only:
+                              - master
+                              - develop
+            - test-run:
+                  filters:
+                      branches:
+                          only:
+                              - master
+                              - develop
+            - test-coverage-codacy:
+                  filters:
+                      branches:
+                          only:
+                              - master
+                              - develop
+                  requires:
+                      - test-run
